version: '{build}'
branches:
  only:
    - main

image: Visual Studio 2019

cache:
  - C:\Users\appveyor\.m2 -> **\pom.xml

install:
  - choco install microsoft-openjdk17
  - set MAVEN_VERSION=3.9.5
  - choco install maven --version %MAVEN_VERSION%
  - refreshenv
  - mvn -version

environment:
  MSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe
  MSTEST_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions\TestPlatform\vstest.console.exe

before_build:
  - nuget restore

build_script:
  - mvn help:effective-pom
  - mvn clean install --batch-mode -DbuildVersion=%APPVEYOR_BUILD_VERSION%
  - ps: if ($env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH) { $env:APPVEYOR_REPO_BRANCH = $env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH; }
  - mvn sonar:sonar -Dsonar.projectKey=lg2de_sonar-scm-tfvc -Dsonar.organization=lg2de -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=%SONAR_TOKEN% -Dsonar.branch.name=%APPVEYOR_REPO_BRANCH%

test: off

artifacts:
- path: sonar-scm-tfvc-plugin/target/*.jar
  name: plugin
- path: SonarTfsAnnotate/bin/Release/SonarTfsAnnotate.exe
  name: proxy
